services:
  mongo:
    image: mongo:7
    container_name: aguia-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: aguia
      MONGO_INITDB_ROOT_PASSWORD: aguia123
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: aguia-mongo-ui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://aguia:aguia123@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

volumes:
  mongo-data:
